Neos:
  ContentRepositoryRegistry:
    presets:
      'default':
        contentGraphProjection:
          catchUpHooks:
            'Neos.Workspace.Ui:TrashBinPopulation':
              factoryObjectName: Neos\Workspace\Ui\Domain\TrashBin\TrashBinPopulationHookFactory
