Neos:
  Flow:
    mvc:
      flashMessages:
        containers:
          'Neos.Restore.Ui:httpHeaderFlashMessages':
            storage: 'Neos\Restore\Ui\Mvc\HttpHeaderFlashMessageStorage'
            requestPatterns:
              'htmx':
                pattern: 'Neos\Restore\Ui\Mvc\HtmxRequestPattern'
